"""
Stock universe configuration — NIFTY 50 + other popular Indian stocks.
Yahoo Finance uses '.NS' suffix for NSE stocks and '.BO' for BSE stocks.
"""

NIFTY50_STOCKS = {
    "RELIANCE": {"name": "Reliance Industries", "sector": "Energy", "yahoo": "RELIANCE.NS"},
    "TCS": {"name": "Tata Consultancy Services", "sector": "IT", "yahoo": "TCS.NS"},
    "HDFCBANK": {"name": "HDFC Bank", "sector": "Banking", "yahoo": "HDFCBANK.NS"},
    "INFY": {"name": "Infosys", "sector": "IT", "yahoo": "INFY.NS"},
    "ICICIBANK": {"name": "ICICI Bank", "sector": "Banking", "yahoo": "ICICIBANK.NS"},
    "HINDUNILVR": {"name": "Hindustan Unilever", "sector": "FMCG", "yahoo": "HINDUNILVR.NS"},
    "SBIN": {"name": "State Bank of India", "sector": "Banking", "yahoo": "SBIN.NS"},
    "BHARTIARTL": {"name": "Bharti Airtel", "sector": "Telecom", "yahoo": "BHARTIARTL.NS"},
    "ITC": {"name": "ITC Limited", "sector": "FMCG", "yahoo": "ITC.NS"},
    "KOTAKBANK": {"name": "Kotak Mahindra Bank", "sector": "Banking", "yahoo": "KOTAKBANK.NS"},
    "LT": {"name": "Larsen & Toubro", "sector": "Capital Goods", "yahoo": "LT.NS"},
    "AXISBANK": {"name": "Axis Bank", "sector": "Banking", "yahoo": "AXISBANK.NS"},
    "WIPRO": {"name": "Wipro", "sector": "IT", "yahoo": "WIPRO.NS"},
    "TATAMOTORS": {"name": "Tata Motors", "sector": "Auto", "yahoo": "TATAMOTORS.NS"},
    "MARUTI": {"name": "Maruti Suzuki India", "sector": "Auto", "yahoo": "MARUTI.NS"},
    "SUNPHARMA": {"name": "Sun Pharmaceutical", "sector": "Pharma", "yahoo": "SUNPHARMA.NS"},
    "TATASTEEL": {"name": "Tata Steel", "sector": "Metals", "yahoo": "TATASTEEL.NS"},
    "ADANIENT": {"name": "Adani Enterprises", "sector": "Diversified", "yahoo": "ADANIENT.NS"},
    "BAJFINANCE": {"name": "Bajaj Finance", "sector": "Finance", "yahoo": "BAJFINANCE.NS"},
    "POWERGRID": {"name": "Power Grid Corporation", "sector": "Power", "yahoo": "POWERGRID.NS"},
    "HCLTECH": {"name": "HCL Technologies", "sector": "IT", "yahoo": "HCLTECH.NS"},
    "ASIANPAINT": {"name": "Asian Paints", "sector": "Consumer", "yahoo": "ASIANPAINT.NS"},
    "BAJAJFINSV": {"name": "Bajaj Finserv", "sector": "Finance", "yahoo": "BAJAJFINSV.NS"},
    "TITAN": {"name": "Titan Company", "sector": "Consumer", "yahoo": "TITAN.NS"},
    "ULTRACEMCO": {"name": "UltraTech Cement", "sector": "Cement", "yahoo": "ULTRACEMCO.NS"},
    "NTPC": {"name": "NTPC Limited", "sector": "Power", "yahoo": "NTPC.NS"},
    "NESTLEIND": {"name": "Nestle India", "sector": "FMCG", "yahoo": "NESTLEIND.NS"},
    "TECHM": {"name": "Tech Mahindra", "sector": "IT", "yahoo": "TECHM.NS"},
    "INDUSINDBK": {"name": "IndusInd Bank", "sector": "Banking", "yahoo": "INDUSINDBK.NS"},
    "M&M": {"name": "Mahindra & Mahindra", "sector": "Auto", "yahoo": "M%26M.NS"},
    "ONGC": {"name": "Oil & Natural Gas Corp", "sector": "Energy", "yahoo": "ONGC.NS"},
    "COALINDIA": {"name": "Coal India", "sector": "Mining", "yahoo": "COALINDIA.NS"},
    "JSWSTEEL": {"name": "JSW Steel", "sector": "Metals", "yahoo": "JSWSTEEL.NS"},
    "ADANIPORTS": {"name": "Adani Ports", "sector": "Infrastructure", "yahoo": "ADANIPORTS.NS"},
    "GRASIM": {"name": "Grasim Industries", "sector": "Cement", "yahoo": "GRASIM.NS"},
    "BPCL": {"name": "Bharat Petroleum", "sector": "Energy", "yahoo": "BPCL.NS"},
    "CIPLA": {"name": "Cipla", "sector": "Pharma", "yahoo": "CIPLA.NS"},
    "DRREDDY": {"name": "Dr. Reddy's Labs", "sector": "Pharma", "yahoo": "DRREDDY.NS"},
    "EICHERMOT": {"name": "Eicher Motors", "sector": "Auto", "yahoo": "EICHERMOT.NS"},
    "DIVISLAB": {"name": "Divi's Laboratories", "sector": "Pharma", "yahoo": "DIVISLAB.NS"},
    "BRITANNIA": {"name": "Britannia Industries", "sector": "FMCG", "yahoo": "BRITANNIA.NS"},
    "HEROMOTOCO": {"name": "Hero MotoCorp", "sector": "Auto", "yahoo": "HEROMOTOCO.NS"},
    "APOLLOHOSP": {"name": "Apollo Hospitals", "sector": "Healthcare", "yahoo": "APOLLOHOSP.NS"},
    "TATACONSUM": {"name": "Tata Consumer Products", "sector": "FMCG", "yahoo": "TATACONSUM.NS"},
    "SBILIFE": {"name": "SBI Life Insurance", "sector": "Insurance", "yahoo": "SBILIFE.NS"},
    "HDFCLIFE": {"name": "HDFC Life Insurance", "sector": "Insurance", "yahoo": "HDFCLIFE.NS"},
    "HINDALCO": {"name": "Hindalco Industries", "sector": "Metals", "yahoo": "HINDALCO.NS"},
    "BAJAJ-AUTO": {"name": "Bajaj Auto", "sector": "Auto", "yahoo": "BAJAJ-AUTO.NS"},
    "WIPRO": {"name": "Wipro", "sector": "IT", "yahoo": "WIPRO.NS"},
    "SHRIRAMFIN": {"name": "Shriram Finance", "sector": "Finance", "yahoo": "SHRIRAMFIN.NS"},
}

# Sector mapping for filters
SECTORS = sorted(list(set(s["sector"] for s in NIFTY50_STOCKS.values())))
